version: '3.2'

volumes:
  cloud-storage:
    driver: local

services:
  postgres:
    image: postgres:9.6
    container_name: cloud-storage
    volumes:
      - type: volume
        source: cloud-storage
        target: /var/lib/postgresql/dataConfig
    environment:
      POSTGRES_DB: cloud-storage
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespass
    ports:
      - "5436:5432"

#  jdbc:postgresql://localhost:5435/cloud-storage